name: Deploy PyMakr

on:
  push:
    branches:
      - master
      - alpha
      - 2.x
      - next

jobs:
  deploy:
    environment: vsce-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - run: npm ci

        # convert package to preview if branch is not master or main
      - name: preparePackage
        run: npm run prepackage
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

      - name: Publish
        # for testing, add --dry-run --debug
        run: npx semantic-release
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN2 }}
          # OVSX_PAT: ${{ secrets.OPEN_VSX }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 